### ISSUE TITLE
Websockets error

### ISSUE THREAD

**Issue by kimgronqvist** [NicolasPetton/jade#10]
Hi, first off - thank you very much for this great package :) 

After upgrading recently, I get these error messages when I try to connect to a running chrome instance:

```
WS Error! on-open (void-function seq-map-indexed)
WS Error! on-message (void-function seq-map-indexed) [4 times]
```

It used to work before, and I don't have devtools open.

I'm on Windows 8.1 using Emacs 25.1.

**Comment by NicolasPetton** [comment]
Indeed, something is wrong with the version of seq.el used.

**Comment by kimgronqvist** [comment]
Awesome, thank you very much :+1:
