### ISSUE TITLE
WS Error!

### ISSUE THREAD

**Issue by fhdhsni** [NicolasPetton/jade#11]
Hi. 
when I try `jade-connect-to-chrome` I get

```
WS Error! on-open (void-function seq-map-indexed)
```

I'm using `emacs 25.1.1` on Manjaro (Arch based) Linux.   Any idea? Thanks

**Comment by NicolasPetton** [comment]
Which version of Jade are you using?

**Comment by fhdhsni** [comment]
It's `20160916.1606`.

**Comment by NicolasPetton** [comment]
> It's `20160916.1606`.

Ok, this version should have a fix for your issue.
How do you load jade.el?

**Comment by fhdhsni** [comment]
I use `use-package`
```
(use-package jade
  :ensure t)
```

**Comment by NicolasPetton** [comment]
Ok, and what do you get (once Jade is loaded) with `M-x
describle-function RET seq-map-indexed RET`?

**Comment by fhdhsni** [comment]
I don't have this function. There're `seq-map`, `seq-mapn` and `seq-mapcat` but not `seq-map-indexed`

**Comment by NicolasPetton** [comment]
> I don't have this function. There're `seq-map`, `seq-mapn` and `seq-mapcat` but not `seq-map-indexed`

I will have a look then, thank you for reporting the issue.

**Comment by fhdhsni** [comment]
I don't know if these are helpful or not, but I'm going to paste it anyway. I deleted my `elpa` directory altogether to make `use-package` install everything from scratch. This is what I got at the end. 
```
Warning (bytecomp): function seq-drop used to take 1+ arguments, now takes 2
Warning (bytecomp): function seq-take used to take 1+ arguments, now takes 2
Warning (bytecomp): function seq-drop-while used to take 2+ arguments, now takes 2
Warning (bytecomp): function seq-empty-p used to take 1+ arguments, now takes 1
Warning (bytecomp): function seq-sort used to take 2+ arguments, now takes 2
Warning (bytecomp): the following functions are not known to be defined:
    seq-map-indexed, seq-sort-by
Warning (bytecomp): the function ‘seq-map-indexed’ is not known to be defined.
```

**Comment by NicolasPetton** [comment]
Thanks, I'll look into it

**Comment by mallt** [comment]
I had the same issue, but manually installing the `seq` package (2.19) resolved it.

**Comment by NicolasPetton** [comment]
Commit https://github.com/NicolasPetton/jade/commit/856846322ea8077ffe6215b54f2f3676db5ccf61 should fix the issue.
