### ISSUE TITLE
Disconnecting kills buffers with active interaction mode

### ISSUE THREAD

**Issue by rcfox** [NicolasPetton/jade#16]
If I enable jade-interaction-mode in a buffer and then eval an expression, that buffer will be killed upon calling jade-quit. This is unexpected and undesirable. If no expressions are eval'd they are not killed.

I think it would be best to leave all jade buffers open, but disable jade-interaction-mode for source buffers and mark the other buffers as read-only.

Using version 20161210.804 from melpa.

**Comment by NicolasPetton** [comment]
Thanks! Should be fixed in master.
