### ISSUE TITLE
jade-connect-to-chrome not available

### ISSUE THREAD

**Issue by Ninerian** [NicolasPetton/jade#17]
Hello,

I followed your instructions until the point

```
M-x jade-connect-to-chrome
```

But the command isn't available. What could be wrong?

I use Emacs 25.1 with prelude installed.

**Comment by NicolasPetton** [comment]
Hi!

Can you tell me a bit more:

- how did you install & load jade?
- do you have any `jade-` command available?
- which version are you running?

**Comment by Ninerian** [comment]
I installed it via  `(prelude-require-packages '(js2-mode json-mode jade))`

the package information:

```
jade-mode is an available package.

     Status: Available from melpa -- [Install]
    Archive: melpa

    Version: 20160525.741
    Summary: Major mode for editing .jade files
   Homepage: https://github.com/brianc/jade-mode
```

M-x jad

```
jade-eval
jade-quit
jade-reload
jade-repl-mode
jade-reconnect
jade-follow-link
jade-repl-return
jade-eval-buffer
jade-repl-inspect
jade-inspector-pop
jade-inspector-mode
jade-eval-last-node
jade-repl-next-input
jade-interaction-mode
jade-inspect-last-node
jade-inspector-refresh
jade-repl-clear-output
jade-repl-previous-input
jade-inspector-next-reference
jade-repl--complete-or-indent
jade-inspector-previous-reference
company-jade-repl
```

Emacs-version: GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0) of 2016-09-17

**Comment by NicolasPetton** [comment]
Ninerian <notifications@github.com> writes:

> I installed it via  `(prelude-require-packages '(js2-mode json-mode
> jade))`

Ok, you need to update Jade then, you're running an old version :)

**Comment by sudarshang** [comment]
@Ninerian you need to have the following  melpa package

http://melpa.org/#/jade

From your comment

> jade-mode is an available package.
>
>     Status: Available from melpa -- [Install]
>    Archive: melpa
>
>    Version: 20160525.741
>    Summary: Major mode for editing .jade files
>   Homepage: https://github.com/brianc/jade-mode

you seem to have installed this one

http://melpa.org/#/jade-mode

**Comment by Ninerian** [comment]
Sorry, I copied the wrong information. Here is the correct one

```
jade is an installed package.

     Status: Installed in ‘jade-20161210.804/’ (unsigned). [Delete]
    Version: 20161210.804
    Summary: JavaScript Awesome Development Environment
   Requires: emacs-25, seq-2.16, js2-mode-20140114, company-0.9.0, websocket-1.6
   Homepage: https://github.com/NicolasPetton/jade
   Keywords: [tools] [javascript]
Other versions: 20161210.804 (melpa).
```

**Comment by NicolasPetton** [comment]
That is weird, `jade-connect-to-chrome` definitely is in this version.

Can you try M-x find-library RET jade-chrome RET and tell me if you
see the function there?

**Comment by Ninerian** [comment]
Here you'll find my emacs files.  

https://github.com/Ninerian/.emacs.d  

Maybe this helps.

**Comment by Ninerian** [comment]
I've found the solution. I had to add `(require 'jade)` to my config. 

Thank you for your help.

**Comment by NicolasPetton** [comment]
You're welcome! Glad you found the issue!
