### ISSUE TITLE
Websocket error when opening a second REPL buffer

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/jade#18]
How to reproduce:

1. open a jade connection on a chrome tab
1. duplicate the tab on chrome
1. close the first one but keep the REPL buffer open
1. open a jade connection to the chrome tab

```
WS Error! on-open (wrong-type-argument stringp nil)
WS Error! on-message (wrong-type-argument integer-or-marker-p nil)
```

```
(setq websocket-debug t)
(setq websocket-callback-debug-on-error t)
```

![screenshot from 2017-03-06 15-04-25](https://cloud.githubusercontent.com/assets/217543/23613084/3e5efc52-027e-11e7-8848-3dd5dac768e3.png)

**Comment by NicolasPetton** [comment]
Commit 7cd3631 should fix the issue.
