### ISSUE TITLE
Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/jade#19]
Sometimes, while debugging, I'm not able to inspect (`C-c M-i` or `C-x C-e`) objects. I always get ` Wrong type argument: arrayp, nil`. Debugging Jade code reveals that `jade-interaction-node-before-point` calls `js2-node-parent` which return nil.

**Comment by NicolasPetton** [comment]
@DamienCassou and I cannot reproduce the issue, so I'm closing it.
