### ISSUE TITLE
Don't show full print string of objects when too long

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/jade#21]
![screenshot from 2017-04-10 10-28-41](https://cloud.githubusercontent.com/assets/217543/24852632/89a019c4-1dd8-11e7-9297-2af146c84857.png)

I think the print string could have `...` at the end when not fitting in a line.

**Comment by NicolasPetton** [comment]
Yes, I will do that. Thanks for reporting it.

**Comment by NicolasPetton** [comment]
@DamienCassou Here's the fix:

![screenshot from 2017-04-10 11-55-58](https://cloud.githubusercontent.com/assets/123539/24856390/e59f176e-1de4-11e7-98f5-452435be841b.png)
