### ISSUE TITLE
Toggling a breakpoint tells me the breakpoint is already there

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/jade#22]
I see a breakpoint in the fringe. I press `C-c b b` to remove it and get

```
Breakpoint at specified location already exists.
```

**Comment by NicolasPetton** [comment]
can you show me where the breakpoint is set and where is the point?
A screenshot would be great.

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> I see a breakpoint in the fringe. I press `C-c b b` to remove it and get
>
> ```
> Breakpoint at specified location already exists.
> ```

Does it happen all the time, or only once?

**Comment by NicolasPetton** [comment]
The issue should be fixed in master.
