### ISSUE TITLE
jade-scratch command missing

### ISSUE THREAD

**Issue by line55** [NicolasPetton/jade#4]
![screenshot from 2016-08-08 00 33 43](https://cloud.githubusercontent.com/assets/468119/17469343/db63bb5c-5cff-11e6-8ff8-b7621812456f.png)

Hi there, 

I can't seem to call the jade-scratch command from the repl.

**Comment by NicolasPetton** [comment]
I think you have to update your version of jade.

**Comment by NicolasPetton** [comment]
It seems that jade-scratch.el was not loaded when loading jade.el.  Can you test with the latest commit? (it will also be on MELPA after the next build)

**Comment by line55** [comment]
Tested with latest MELPA version, works! Many thanks!
👍
